	// File generated by MineTweakerRecipeMaker
	//                     READ THIS HEADER BEFORE EDITING ANYTHING
	// ================================================================================
	//     This file is read and changed by the mod.
	//     If you remove/edit any of the markers, IT WILL STOP WORKING!
	//     If you want to make manual edits, make a backup of this file!
	//     Markers look like this: "//#MARKER something"
	//     They indicate where calls should be placed, so that MineTweaker does them in the correct order.
	//     Removes come first, then stuff is added.
	// ================================================================================
	//

	// ================================================================================
	//#MARKER REMOVE

	// ================================================================================
	//#MARKER REMOVE SHAPELESS

	// ================================================================================
	//#MARKER REMOVE SHAPED

	// ================================================================================
	//#MARKER ADD

	// ================================================================================
	//#MARKER ADD SHAPELESS

	// ================================================================================
	//#MARKER ADD SHAPED
	import crafttweaker.block.IBlock;
	import mods.modularmachinery.RecipePrimer;
	import mods.modularmachinery.RecipeBuilder;
	import crafttweaker.item.IItemStack;
	import crafttweaker.item.IIngredient;
	import crafttweaker.liquid.ILiquidStack;
	import crafttweaker.oredict.IOreDictEntry;
	import crafttweaker.item.IItemDefinition;
	import crafttweaker.events.IEventManager;
	import crafttweaker.container.IContainer;




	RecipeBuilder.newBuilder("chemplant_1001", "chemplant",1).
	addItemInput(<ore:oreCoal>).
	addFluidInput(<liquid:acid> *500).
	addFluidInput(<liquid:sulfuric_acid> *500).
	addItemOutput(<hbm:ore_bedrock_enriched:7>*2).
	addItemOutput(<hbm:ore_bedrock_enriched:4>*2).setChance(0.4).
	addItemOutput(<hbm:ore_bedrock_enriched:20>*2).setChance(0.2).
	addEnergyPerTickInput(50000).
	build();	
	RecipeBuilder.newBuilder("chemplant_1002", "chemplant",1).
	addItemInput(<ore:oreRedstone>).
	addFluidInput(<liquid:acid> *500).
	addFluidInput(<liquid:sulfuric_acid> *500).
	addItemOutput(<hbm:ore_bedrock_enriched:7>*2).setChance(0.4).
	addItemOutput(<hbm:ore_bedrock_enriched:4>*2).
	addItemOutput(<hbm:ore_bedrock_enriched:20>*2).setChance(0.1).
	addEnergyPerTickInput(50000).
	build();	
	RecipeBuilder.newBuilder("chemplant_1003", "chemplant",1).
	addItemInput(<ore:oreSulfur>).
	addFluidInput(<liquid:acid> *500).
	addFluidInput(<liquid:sulfuric_acid> *500).
	addItemOutput(<hbm:ore_bedrock_enriched:7>*2).setChance(0.2).
	addItemOutput(<hbm:ore_bedrock_enriched:4>*2).setChance(0.2).
	addItemOutput(<hbm:ore_bedrock_enriched:20>*2).
	addEnergyPerTickInput(50000).
	build();		
	
	RecipeBuilder.newBuilder("chemplant_1004", "chemplant",1).
	addItemInput(<ore:oreTitanium>).
	addFluidInput(<liquid:acid> *500).
	addFluidInput(<liquid:sulfuric_acid> *500).
	addItemOutput(<hbm:ore_bedrock_enriched:10>*2).
	addItemOutput(<hbm:ore_bedrock_enriched:1>*2).setChance(0.4).
	addItemOutput(<hbm:ore_bedrock_enriched:8>*2).setChance(0.05).
	addItemOutput(<hbm:ore_bedrock_enriched:45>*2).setChance(0.05).
	addEnergyPerTickInput(50000).
	build();	
	RecipeBuilder.newBuilder("chemplant_1005", "chemplant",1).
	addItemInput(<ore:oreIron>).
	addFluidInput(<liquid:acid> *500).
	addFluidInput(<liquid:sulfuric_acid> *500).
	addItemOutput(<hbm:ore_bedrock_enriched:10>*2).setChance(0.4).
	addItemOutput(<hbm:ore_bedrock_enriched:1>*2).
	addItemOutput(<hbm:ore_bedrock_enriched:8>*2).setChance(0.2).
	addItemOutput(<hbm:ore_bedrock_enriched:45>*2).setChance(0.2).
	addEnergyPerTickInput(50000).
	build();	
	RecipeBuilder.newBuilder("chemplant_1006", "chemplant",1).
	addItemInput(<ore:oreManganese>).
	addFluidInput(<liquid:acid> *500).
	addFluidInput(<liquid:sulfuric_acid> *500).
	addItemOutput(<hbm:ore_bedrock_enriched:10>*2).setChance(0.1).
	addItemOutput(<hbm:ore_bedrock_enriched:1>*2).setChance(0.4).
	addItemOutput(<hbm:ore_bedrock_enriched:8>*2).setChance(0.7).
	addItemOutput(<hbm:ore_bedrock_enriched:45>*2).setChance(0.3).
	addEnergyPerTickInput(50000).
	build();	
	RecipeBuilder.newBuilder("chemplant_1007", "chemplant",1).
	addItemInput(<ore:orePolymetal>).
	addFluidInput(<liquid:acid> *500).
	addFluidInput(<liquid:sulfuric_acid> *500).
	addItemOutput(<hbm:ore_bedrock_enriched:10>*2).setChance(0.1).
	addItemOutput(<hbm:ore_bedrock_enriched:1>*2).setChance(0.4).
	addItemOutput(<hbm:ore_bedrock_enriched:8>*2).setChance(0.3).
	addItemOutput(<hbm:ore_bedrock_enriched:45>*2).setChance(0.7).
	addEnergyPerTickInput(50000).
	build();	

	RecipeBuilder.newBuilder("chemplant_1008", "chemplant",1).
	addItemInput(<ore:oreBeryllium>).
	addFluidInput(<liquid:acid> *500).
	addFluidInput(<liquid:sulfuric_acid> *500).
	addItemOutput(<hbm:ore_bedrock_enriched:15>*2).
	addItemOutput(<hbm:ore_bedrock_enriched:18>*2).setChance(0.2).
	addItemOutput(<hbm:ore_bedrock_enriched:5>*2).setChance(0.3).
	addEnergyPerTickInput(50000).
	build();	
	RecipeBuilder.newBuilder("chemplant_1009", "chemplant",1).
	addItemInput(<ore:oreLithium>).
	addFluidInput(<liquid:acid> *500).
	addFluidInput(<liquid:sulfuric_acid> *500).
	addItemOutput(<hbm:ore_bedrock_enriched:15>*2).setChance(0.2).
	addItemOutput(<hbm:ore_bedrock_enriched:18>*2).
	addItemOutput(<hbm:ore_bedrock_enriched:5>*2).setChance(0.2).
	addEnergyPerTickInput(50000).
	build();	
	RecipeBuilder.newBuilder("chemplant_1010", "chemplant",1).
	addItemInput(<ore:oreEmerald>).
	addFluidInput(<liquid:acid> *500).
	addFluidInput(<liquid:sulfuric_acid> *500).
	addItemOutput(<hbm:ore_bedrock_enriched:15>*2).setChance(0.4).
	addItemOutput(<hbm:ore_bedrock_enriched:18>*2).setChance(0.2).
	addItemOutput(<hbm:ore_bedrock_enriched:5>*2).
	addEnergyPerTickInput(50000).
	build();		

	RecipeBuilder.newBuilder("chemplant_1011", "chemplant",1).
	addItemInput(<ore:oreQuartz>).
	addFluidInput(<liquid:acid> *500).
	addFluidInput(<liquid:sulfuric_acid> *500).
	addItemOutput(<hbm:ore_bedrock_enriched:6>*2).
	addItemOutput(<hbm:ore_bedrock_enriched:27>*2).setChance(0.3).
	addItemOutput(<hbm:ore_bedrock_enriched:43>*2).setChance(0.2).
	addEnergyPerTickInput(50000).
	build();	
	RecipeBuilder.newBuilder("chemplant_1012", "chemplant",1).
	addItemInput(<ore:oreAsbestos>).
	addFluidInput(<liquid:acid> *500).
	addFluidInput(<liquid:sulfuric_acid> *500).
	addItemOutput(<hbm:ore_bedrock_enriched:6>*2).setChance(0.3).
	addItemOutput(<hbm:ore_bedrock_enriched:27>*2).
	addItemOutput(<hbm:ore_bedrock_enriched:43>*2).setChance(0.2).
	addEnergyPerTickInput(50000).
	build();	
	RecipeBuilder.newBuilder("chemplant_1013", "chemplant",1).
	addItemInput(<ore:oreBorax>).
	addFluidInput(<liquid:acid> *500).
	addFluidInput(<liquid:sulfuric_acid> *500).
	addItemOutput(<hbm:ore_bedrock_enriched:6>*2).setChance(0.2).
	addItemOutput(<hbm:ore_bedrock_enriched:27>*2).setChance(0.2).
	addItemOutput(<hbm:ore_bedrock_enriched:43>*2).
	addEnergyPerTickInput(50000).
	build();	


	RecipeBuilder.newBuilder("chemplant_1014", "chemplant",1).
	addItemInput(<ore:oreCinnabar>).
	addFluidInput(<liquid:acid> *500).
	addFluidInput(<liquid:sulfuric_acid> *500).
	addItemOutput(<hbm:ore_bedrock_enriched:42>*2).
	addItemOutput(<hbm:ore_bedrock_enriched>*2).setChance(0.4).
	addItemOutput(<hbm:ore_bedrock_enriched:11>*2).setChance(0.2).
	addEnergyPerTickInput(50000).
	build();	
	RecipeBuilder.newBuilder("chemplant_1015", "chemplant",1).
	addItemInput(<ore:oreGold>).
	addFluidInput(<liquid:acid> *500).
	addFluidInput(<liquid:sulfuric_acid> *500).
	addItemOutput(<hbm:ore_bedrock_enriched:42>*2).setChance(0.3).
	addItemOutput(<hbm:ore_bedrock_enriched>*2).
	addItemOutput(<hbm:ore_bedrock_enriched:11>*2).setChance(0.3).
	addEnergyPerTickInput(50000).
	build();	
	RecipeBuilder.newBuilder("chemplant_1016", "chemplant",1).
	addItemInput(<ore:oreCopper>).
	addFluidInput(<liquid:acid> *500).
	addFluidInput(<liquid:sulfuric_acid> *500).
	addItemOutput(<hbm:ore_bedrock_enriched:42>*2).setChance(0.3).
	addItemOutput(<hbm:ore_bedrock_enriched>*2).setChance(0.3).
	addItemOutput(<hbm:ore_bedrock_enriched:11>*2).
	addEnergyPerTickInput(50000).
	build();	

	RecipeBuilder.newBuilder("chemplant_1017", "chemplant",1).
	addItemInput(<ore:oreDiamond>).
	addFluidInput(<liquid:acid> *500).
	addFluidInput(<liquid:sulfuric_acid> *500).
	addItemOutput(<hbm:ore_bedrock_enriched:3>*2).
	addItemOutput(<hbm:ore_bedrock_enriched:44>*2).setChance(0.3).
//	addItemOutput(<hbm:ore_bedrock_enriched:11>*2).setChance(0.2).
	addEnergyPerTickInput(50000).
	build();	
	RecipeBuilder.newBuilder("chemplant_1018", "chemplant",1).
	addItemInput(<ore:oreVolcanic>).
	addFluidInput(<liquid:acid> *500).
	addFluidInput(<liquid:sulfuric_acid> *500).
	addItemOutput(<hbm:ore_bedrock_enriched:3>*2).setChance(0.3).
	addItemOutput(<hbm:ore_bedrock_enriched:44>*2).
//	addItemOutput(<hbm:ore_bedrock_enriched:11>*2).setChance(0.3).
	addEnergyPerTickInput(50000).
	build();	
//	RecipeBuilder.newBuilder("chemplant_1019", "chemplant",1).
//	addItemInput(<ore:oreCopper>).
//	addFluidInput(<liquid:acid> *500).
//	addFluidInput(<liquid:sulfuric_acid> *500).
//	addItemOutput(<hbm:ore_bedrock_enriched:42>*2).setChance(0.3).
//	addItemOutput(<hbm:ore_bedrock_enriched>*2).setChance(0.3).
//	addItemOutput(<hbm:ore_bedrock_enriched:11>*2).
//	addEnergyPerTickInput(50000).
//	build();

	RecipeBuilder.newBuilder("chemplant_1020", "chemplant",1).
	addItemInput(<ore:oreTungsten>).
	addFluidInput(<liquid:acid> *500).
	addFluidInput(<liquid:sulfuric_acid> *500).
	addItemOutput(<hbm:ore_bedrock_enriched:12>*2).
	addItemOutput(<hbm:ore_bedrock_enriched:9>*2).setChance(0.2).
	addItemOutput(<hbm:ore_bedrock_enriched:13>*2).setChance(0.4).
	addEnergyPerTickInput(50000).
	build();	
	RecipeBuilder.newBuilder("chemplant_1021", "chemplant",1).
	addItemInput(<ore:oreAluminum>).
	addFluidInput(<liquid:acid> *500).
	addFluidInput(<liquid:sulfuric_acid> *500).
	addItemOutput(<hbm:ore_bedrock_enriched:12>*2).setChance(0.3).
	addItemOutput(<hbm:ore_bedrock_enriched:9>*2).
	addItemOutput(<hbm:ore_bedrock_enriched:13>*2).setChance(0.2).
	addEnergyPerTickInput(50000).
	build();	
	RecipeBuilder.newBuilder("chemplant_1022", "chemplant",1).
	addItemInput(<ore:oreLead>).
	addFluidInput(<liquid:acid> *500).
	addFluidInput(<liquid:sulfuric_acid> *500).
	addItemOutput(<hbm:ore_bedrock_enriched:12>*2).setChance(0.4).
	addItemOutput(<hbm:ore_bedrock_enriched:9>*2).setChance(0.2).
	addItemOutput(<hbm:ore_bedrock_enriched:13>*2).
	addEnergyPerTickInput(50000).
	build();		

//	RecipeBuilder.newBuilder("chemplant_1023", "chemplant",1).
//	addItemInput(<ore:oreArsenic>).
//	addFluidInput(<liquid:acid> *500).
//	addFluidInput(<liquid:sulfuric_acid> *500).
//	addItemOutput(<hbm:ore_bedrock_enriched:12>*2).
//	addItemOutput(<hbm:ore_bedrock_enriched:9>*2).setChance(0.2).
//	addItemOutput(<hbm:ore_bedrock_enriched:13>*2).setChance(0.4).
//	addEnergyPerTickInput(50000).
//	build();	
	RecipeBuilder.newBuilder("chemplant_1024", "chemplant",1).
	addItemInput(<ore:oreSaltpeter>).
	addFluidInput(<liquid:acid> *500).
	addFluidInput(<liquid:sulfuric_acid> *500).
//	addItemOutput(<hbm:ore_bedrock_enriched:12>*2).setChance(0.3).
	addItemOutput(<hbm:ore_bedrock_enriched:21>*2).
	addItemOutput(<hbm:ore_bedrock_enriched:19>*2).setChance(0.4).
	addEnergyPerTickInput(50000).
	build();	
	RecipeBuilder.newBuilder("chemplant_1025", "chemplant",1).
	addItemInput(<ore:oreRedPhosphorus>).
	addFluidInput(<liquid:acid> *500).
	addFluidInput(<liquid:sulfuric_acid> *500).
//	addItemOutput(<hbm:ore_bedrock_enriched:12>*2).setChance(0.4).
	addItemOutput(<hbm:ore_bedrock_enriched:21>*2).setChance(0.3).
	addItemOutput(<hbm:ore_bedrock_enriched:19>*2).
	addEnergyPerTickInput(50000).
	build();	


	RecipeBuilder.newBuilder("chemplant_2001", "chemplant",1).
	addItemInput(<hbm:waste_np237>*2).
	addItemOutput(<hbm:nugget_bismuth>).
	addItemOutput(<hbm:nugget_technetium>*3).
	addItemOutput(<hbm:nugget_pu238>).
	addItemOutput(<hbm:nugget_pu239>*3).
	addEnergyPerTickInput(0).
	build();
	RecipeBuilder.newBuilder("chemplant_2002", "chemplant",1).
	addItemInput(<hbm:waste_euph>*2).
	addItemOutput(<hbm:particle_digamma>).
	addItemOutput(<hbm:nugget_dineutronium>*2).
	addItemOutput(<hbm:powder_tennessine>).setChance(0.44).
	addEnergyPerTickInput(0).
	build();
	RecipeBuilder.newBuilder("chemplant_2003", "chemplant",1).
	addItemInput(<hbm:waste_sa327>*2).
	addItemOutput(<hbm:nugget_tantalium>*4).
	addItemOutput(<hbm:nugget_gh336>).
	addItemOutput(<hbm:nugget_euphemium>*2).
	addItemOutput(<hbm:powder_astatine>).setChance(0.11).
	addEnergyPerTickInput(0).
	build();
	RecipeBuilder.newBuilder("chemplant_2004", "chemplant",1).
	addItemInput(<hbm:waste_pb209>*2).
	addItemOutput(<hbm:nugget_bismuth>*4).
	addItemOutput(<hbm:nugget_gh336>).
	addItemOutput(<hbm:nugget_mercury>).
	addItemOutput(<hbm:powder_balefire>).
	addEnergyPerTickInput(0).
	build();
	RecipeBuilder.newBuilder("chemplant_2005", "chemplant",1).
	addItemInput(<hbm:waste_pu239>*2).
	addItemOutput(<hbm:nugget_bismuth>).
	addItemOutput(<hbm:nugget_technetium>*3).
	addItemOutput(<hbm:powder_cerium_tiny>*2).
	addItemOutput(<hbm:powder_iodine_tiny>*2).
	addEnergyPerTickInput(0).
	build();
	RecipeBuilder.newBuilder("chemplant_2006", "chemplant",1).
	addItemInput(<hbm:bred_lead>).
	addItemOutput(<hbm:nugget_bismuth>*4).
	addItemOutput(<hbm:nugget_pb209>*2).
	addEnergyPerTickInput(1000).
	build();
	RecipeBuilder.newBuilder("chemplant_2007", "chemplant",1).
	addItemInput(<hbm:bred_bismuth>*2).
	addItemOutput(<hbm:powder_tennessine>).setChance(0.11).
	addItemOutput(<hbm:powder_astatine>).setChance(0.33).
	addItemOutput(<hbm:powder_caesium_tiny>*3).
	addItemOutput(<hbm:powder_iodine_tiny>*3).
	addEnergyPerTickInput(0).
	build();